title: Jerry Busser
email: jerry.busser@gmail.com
description: >
  I like Rails, EmberJS, Heroku, and vim.
baseurl: ''
url: 'http://jbusser.github.io'
twitter_username: stirredstrained
github_username: jbusser
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, bin]
